name: payment-tests

on:
  pull_request:
    paths:
      - "payment/**"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_KEY: ${{ secrets.JWT_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: cd payment && npm install && npm run test:ci
